spring.application.name=gerenciamento_ferias
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=3002
spring.datasource.url=jdbc:sqlserver://OBRMSREP01:1433;databaseName=acessos;TrustServerCertificate=true
spring.datasource.username=obr_acesso
spring.datasource.password=Magna@240
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=${ACTIVE_PROFILE:dev}